### ISSUE TITLE
Missing extensions

### ISSUE THREAD

**Issue by DAThosting** [DiroHost/whmcs-whoislist#4]
.e49
.gr (Error: -)
.hr (Error: -)
.irish
.jetzt
.jobs (Error: 0 - php_network_getaddresses: getaddrinfo failed: Name or service not known)
.me (Error: 110 - Connection timed out)
.meet
.party
.pro (Error: 110 - Connection timed out)
.qpon
.science
.site
.tech
.trade
.webcam
.za

**Comment by arcronis** [comment]
All are added, only .gr and .e49 is missing.

Found no Whois Server for both Domains.
